import os
import sys
import stat

def install():
    # Find the repository's root .git directory relative to this script
    current_dir = os.path.abspath(os.path.dirname(__file__))
    git_dir = os.path.abspath(os.path.join(current_dir, "..", ".git"))
    
    if not os.path.exists(git_dir):
        print("Error: Could not find .git directory. Are you running this script inside your repository?")
        sys.exit(1)
        
    hooks_dir = os.path.join(git_dir, "hooks")
    if not os.path.exists(hooks_dir):
        os.makedirs(hooks_dir)
        
    hook_path = os.path.join(hooks_dir, "pre-push")
    
    # The pre-push hook script content.
    # It attempts to auto-detect standard Python virtual environments to avoid import/environment errors.
    hook_content = """#!/bin/sh
# Git pre-push hook generated by Code Review Agent installer.
# Evaluates unpushed commits for quality/security before pushing.

# Determine the correct Python interpreter (prioritizes local virtual environments)
PYTHON_EXEC="python"

if [ -f "./.venv/bin/python" ]; then
    PYTHON_EXEC="./.venv/bin/python"
elif [ -f "./venv/bin/python" ]; then
    PYTHON_EXEC="./venv/bin/python"
elif [ -f "./.venv/Scripts/python.exe" ]; then
    # Windows compatibility (Git Bash)
    PYTHON_EXEC="./.venv/Scripts/python.exe"
elif [ -f "./venv/Scripts/python.exe" ]; then
    PYTHON_EXEC="./venv/Scripts/python.exe"
fi

echo ""
echo "========================================="
echo "  Running Code Review Agent Pre-Push...  "
echo "========================================="
echo ""

$PYTHON_EXEC code-review-agent/main.py analyze

# Exit 0 ensures the push process is never forcefully blocked
# even if suggestions are found or if the API is unreachable.
exit 0
"""
    
    try:
        with open(hook_path, "w", encoding="utf-8") as f:
            f.write(hook_content)
            
        # Grant executable permissions to the hook file (similar to chmod +x)
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        
        print(f"Git pre-push hook successfully installed at: {hook_path}")
    except Exception as e:
        print(f"Failed to install Git hook: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    install()